const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_OTP: "/verify-otp",
  DASHBOARD: "/dashboard",
  MARKETPLACE: "/marketplace",
  INVESTMENTS: "/investments",
  WALLET: "/wallet",
  WITHDRAWALS: "/withdrawals",
  DEPOSITS: "/deposits",
  PROFILE: "/profile",
  ADMIN: "/admin",
  ADMIN_ASSETS: "/admin/assets",
  ADMIN_SHARES: "/admin/shares",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_PROFIT: "/admin/profit",
  ADMIN_DEPOSITS: "/admin/deposits",
  ADMIN_INVESTORS: "/admin/investors",
  ADMIN_INVESTOR_DETAILS: "/admin/investors/:investorId",
  ADMIN_WITHDRAWALS: "/admin/withdrawals",
  ADMIN_AUDIT: "/admin/audit",
  ADMIN_PENDING_APPROVALS: "/admin/users/pending",
  ADMIN_SETTINGS: "/admin/settings",
  UNAUTHORIZED: "/unauthorized",
};

export default ROUTES;
